In [6]:
import numpy as np
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
ls

drive/  sample_data/


In [4]:
cd /content/drive/MyDrive/Colab Notebooks/GIthub/AI_School

/content/drive/MyDrive/Colab Notebooks/GIthub/AI_School


In [5]:
ls

README.md  test2.ipynb  test.ipynb  TP1/


In [7]:
arr1 = np.full(6, 7)

In [8]:
print(arr1)

[7 7 7 7 7 7]


In [13]:
arr2 = np.random.random(6)

In [14]:
print(arr2)

[0.87458277 0.49234861 0.24969257 0.01125524 0.67145795 0.12631952]


In [15]:
arr3 = np.arange(3, 17, 3)
print(arr3)

[ 3  6  9 12 15]


In [ ]:
!git ad