In [1]:
import numpy as np

In [2]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [3]:
a.sum()

4.8595784

In [4]:
a.min()

0.05093587

In [5]:
a.std()

0.21392120766089617

In [6]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [11]:
for arr_1d in a:
    print(min(arr_1d))

0.17296777
0.05093587
0.12697628


In [12]:
a.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [13]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [14]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data * ones

array([[1, 2],
       [3, 4]])

In [20]:
data = np.array([[1, 2], [3, 4], [5, 6]])
twos_col = np.array([[2], [2], [2]])
data + twos_col

array([[3, 4],
       [5, 6],
       [7, 8]])

In [21]:
np.zeros((3, 2, 2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [22]:
np.zeros((3, 2, 2)).shape

(3, 2, 2)

In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.flip(arr)

array([8, 7, 6, 5, 4, 3, 2, 1])

In [25]:
arr_2d = np.array([[1, 2, 3, 4], 
									 [5, 6, 7, 8], 
									 [9, 10, 11, 12]])

In [27]:
reversed_arr = np.flip(arr_2d)
reversed_arr

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [28]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [29]:
print(np.unique(a))

[11 12 13 14 15 16 17 18 19 20]


In [30]:
print(np.unique(a, return_index=True))

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]), array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14]))


In [31]:
np.unique(a, return_counts=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1]))

In [33]:
rng.integers(5, size=(2, 4))

NameError: name 'rng' is not defined

In [34]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [35]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [18]:
import os
import sys
import urllib.request
import json

client_id = "" # 개발자센터에서 발급받은 Client ID 값
client_secret = "" # 개발자센터에서 발급받은 Client Secret 값
encText = urllib.parse.quote("반갑습니다")
data = "source=ko&target=en&text=" + encText
url = "https://openapi.naver.com/v1/papago/n2mt"
request = urllib.request.Request(url)
request.add_header("X-Naver-Client-Id",client_id)
request.add_header("X-Naver-Client-Secret",client_secret)
response = urllib.request.urlopen(request, data=data.encode("utf-8"))
rescode = response.getcode()
if(rescode==200):
    response_body = response.read()
    json_res = response_body.decode('utf-8')
    
    json_to_dict = json.loads(json_res)
    translated_text = json_to_dict["message"]["result"]["translatedText"]
    print(translated_text)
else:
    print("Error Code:" + rescode)

Nice to meet you.


[key](https://developers.naver.com/apps/#/myapps/TiXmVlMmg4qE9ylDaKY2/overview)

In [28]:
import os
import sys
import urllib.request
import json


client_id = "" 
client_secret = "" 

def translate_kr_to_en(client_id, client_secret, korean):
    client_id = client_id
    client_secret = client_secret
    encText = urllib.parse.quote(korean)
    data = "source=ko&target=en&text=" + encText
    url = "https://openapi.naver.com/v1/papago/n2mt"
    request = urllib.request.Request(url)
    request.add_header("X-Naver-Client-Id",client_id)
    request.add_header("X-Naver-Client-Secret",client_secret)
    response = urllib.request.urlopen(request, data=data.encode("utf-8"))
    rescode = response.getcode()
    if(rescode==200):
        response_body = response.read()
        json_res = response_body.decode('utf-8')
        
        json_to_dict = json.loads(json_res)
        translated_text = json_to_dict["message"]["result"]["translatedText"]
        
        return translated_text
    else:
        error_msg = "Error Code:" + rescode
        return error_msg

def translate_en_to_kr(client_id, client_secret, korean):
    client_id = client_id
    client_secret = client_secret
    encText = urllib.parse.quote(korean)
    data = "source=en&target=ko&text=" + encText
    url = "https://openapi.naver.com/v1/papago/n2mt"
    request = urllib.request.Request(url)
    request.add_header("X-Naver-Client-Id",client_id)
    request.add_header("X-Naver-Client-Secret",client_secret)
    response = urllib.request.urlopen(request, data=data.encode("utf-8"))
    rescode = response.getcode()
    if(rescode==200):
        response_body = response.read()
        json_res = response_body.decode('utf-8')
        
        json_to_dict = json.loads(json_res)
        translated_text = json_to_dict["message"]["result"]["translatedText"]
        
        return translated_text
    else:
        error_msg = "Error Code:" + rescode
        return error_msg

def translate_kr_to_jn(client_id, client_secret, korean):
    client_id = client_id
    client_secret = client_secret
    encText = urllib.parse.quote(korean)
    data = "source=ko&target=ja&text=" + encText
    url = "https://openapi.naver.com/v1/papago/n2mt"
    request = urllib.request.Request(url)
    request.add_header("X-Naver-Client-Id",client_id)
    request.add_header("X-Naver-Client-Secret",client_secret)
    response = urllib.request.urlopen(request, data=data.encode("utf-8"))
    rescode = response.getcode()
    if(rescode==200):
        response_body = response.read()
        json_res = response_body.decode('utf-8')
        
        json_to_dict = json.loads(json_res)
        translated_text = json_to_dict["message"]["result"]["translatedText"]
        
        return translated_text
    else:
        error_msg = "Error Code:" + rescode
        return error_msg

def translate_jn_to_kr(client_id, client_secret, korean):
    client_id = client_id
    client_secret = client_secret
    encText = urllib.parse.quote(korean)
    data = "source=ja&target=ko&text=" + encText
    url = "https://openapi.naver.com/v1/papago/n2mt"
    request = urllib.request.Request(url)
    request.add_header("X-Naver-Client-Id",client_id)
    request.add_header("X-Naver-Client-Secret",client_secret)
    response = urllib.request.urlopen(request, data=data.encode("utf-8"))
    rescode = response.getcode()
    if(rescode==200):
        response_body = response.read()
        json_res = response_body.decode('utf-8')
        
        json_to_dict = json.loads(json_res)
        translated_text = json_to_dict["message"]["result"]["translatedText"]
        
        return translated_text
    else:
        error_msg = "Error Code:" + rescode
        return error_msg

In [25]:
text = "동해물과 백두산이 마르고 닳도록 하느님이 보우하사 우리나라 만세"
translate_kr_to_en(client_id, client_secret, text)

"Until the day when the East Sea's waters and Baekdusan Mountain are dry and worn away, god protect and preserve our nation."

In [31]:
text = "동해물과 백두산이 마르고 닳도록 하느님이 보우하사 우리나라 만세"
jp = translate_kr_to_jn(client_id, client_secret, text)
jp

'東海の水と白頭山が乾くまで神様が歩こう我が国万歳'

In [32]:
translate_jn_to_kr(client_id, client_secret, jp)

'동해물과 백두산이 마를 때까지 하나님이 걷자 우리나라 만세'

In [24]:
text = "Down in dry county They're swimming in the sand Praying for some holy water To wash the sins from off our hands"
translate_en_to_kr(client_id, client_secret, text)

'그들은 모래 속에서 헤엄치고 있어 성수를 빌어 우리 손에서 죄를 씻어내고 있어'