In [1]:
import numpy as np

In [2]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [3]:
a.sum()

4.8595784

In [4]:
a.min()

0.05093587

In [5]:
a.std()

0.21392120766089617

In [6]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [11]:
for arr_1d in a:
    print(min(arr_1d))

0.17296777
0.05093587
0.12697628


In [12]:
a.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [13]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [14]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data * ones

array([[1, 2],
       [3, 4]])

In [20]:
data = np.array([[1, 2], [3, 4], [5, 6]])
twos_col = np.array([[2], [2], [2]])
data + twos_col

array([[3, 4],
       [5, 6],
       [7, 8]])

In [21]:
np.zeros((3, 2, 2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [22]:
np.zeros((3, 2, 2)).shape

(3, 2, 2)

In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.flip(arr)

array([8, 7, 6, 5, 4, 3, 2, 1])

In [25]:
arr_2d = np.array([[1, 2, 3, 4], 
									 [5, 6, 7, 8], 
									 [9, 10, 11, 12]])

In [27]:
reversed_arr = np.flip(arr_2d)
reversed_arr

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [28]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [29]:
print(np.unique(a))

[11 12 13 14 15 16 17 18 19 20]


In [30]:
print(np.unique(a, return_index=True))

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]), array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14]))


In [31]:
np.unique(a, return_counts=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1]))

In [33]:
rng.integers(5, size=(2, 4))

NameError: name 'rng' is not defined

In [34]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [35]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [4]:
import tensorflow as tf

cifar = tf.keras.datasets.cifar100
(x_train, y_train), (x_test, y_test) = cifar.load_data()
model = tf.keras.applications.ResNet50(
    include_top=True,
    weights=None,
    input_shape=(32, 32, 3),
    classes=100,)

loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
model.compile(optimizer="adam", loss=loss_fn, metrics=["accuracy"])
model.fit(x_train, y_train, epochs=5, batch_size=64)

Epoch 1/5


2022-12-11 16:24:40.960422: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


KeyboardInterrupt: 

In [1]:
from sklearn.model_selection import train_test_split

train_test_split

ValueError: At least one array required as input