# 유튜브 강의 실습 파일
[강의 링크](https://www.youtube.com/watch?v=auCw6qikSYs&list=PLl1irxoYh2wyLwJutUZx5Q_QEEDZoXBnz&index=2&ab_channel=%EB%B4%89%EC%88%98%EA%B3%A8%EA%B0%9C%EB%B0%9C%EC%9E%90%EC%9D%B4%EC%84%A0%EB%B9%84)

# 데이터 불러오기

In [1]:
import pandas as pd

In [2]:
파일경로 = "https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv"
레모네이드 = pd.read_csv(파일경로)

파일경로 = "https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv"
보스턴 = pd.read_csv(파일경로)

파일경로 = "https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv"
아이리스 = pd.read_csv(파일경로)

In [3]:
print(레모네이드.shape)
print(보스턴.shape)
print(아이리스.shape)

(6, 2)
(506, 14)
(150, 5)


In [4]:
# col 이름 출력
print(레모네이드.columns)
print(보스턴.columns)
print(아이리스.columns)

Index(['온도', '판매량'], dtype='object')
Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')
Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종'], dtype='object')


In [5]:
독립_레몬 = 레모네이드[["온도"]]
종속_레몬 = 레모네이드[["판매량"]]
print(독립_레몬.shape, 종속_레몬.shape)

독립_보스턴 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 
              'dis', 'rad', 'tax', 'ptratio', 'b', 'lstat']]
종속_보스턴 = 보스턴[['medv']]
print(독립_보스턴.shape, 종속_보스턴.shape)

독립_아이리스 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속_아이리스 = 아이리스[['품종']]
print(독립_아이리스.shape, 종속_아이리스.shape)

(6, 1) (6, 1)
(506, 13) (506, 1)
(150, 4) (150, 1)


In [6]:
레모네이드.head()

온도  판매량
0  20   40
1  21   42
2  22   44
3  23   46
4  24   48

In [7]:
보스턴.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [8]:
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

# 레모네이드 판매 예측

In [9]:
import tensorflow as tf

In [10]:
# 1의 의미 : 독립변수의 개수
X = tf.keras.layers.Input(shape=[1])

# 1의 의미 : 종속변수의 개수
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss="mse")

In [ ]:
# 모델 학습
# epochs : 전체 데이터를 몇 번 학습할 것인가
model.fit(독립_레몬, 종속_레몬, epochs=5000)

In [17]:
# 모델을 이용하여 예측
model.predict(독립_레몬)

1/1 [==============================] - 0s 55ms/step


array([[40.119514],
       [42.07846 ],
       [44.037403],
       [45.99635 ],
       [47.95529 ],
       [49.914238]], dtype=float32)

In [18]:
model.predict([[15]])

1/1 [==============================] - 0s 85ms/step


array([[30.324795]], dtype=float32)

# 보스턴 집 값 예측

In [20]:
# shape=[독립 변수의 개수]
X = tf.keras.layers.Input(shape=[13])

# Dense(종속변수의 개수)
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [ ]:
model.fit(독립_보스턴, 종속_보스턴, epochs=1000)

In [25]:
print("Predictions: ", model.predict(독립_보스턴[0:5]))

1/1 [==============================] - 0s 32ms/step
Predictions:  [[29.626162]
 [24.839338]
 [30.755053]
 [29.89682 ]
 [29.343779]]


In [26]:
종속_보스턴[0:5]

medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2

In [27]:
# 모델이 수식 확인
model.get_weights()

[array([[-0.08952659],
        [ 0.0676296 ],
        [-0.05143153],
        [ 3.2793136 ],
        [ 1.2416283 ],
        [ 4.3660736 ],
        [ 0.00910801],
        [-0.9312572 ],
        [ 0.15672179],
        [-0.00877861],
        [-0.08771978],
        [ 0.01564242],
        [-0.5490848 ]], dtype=float32), array([2.678095], dtype=float32)]

In [30]:
# 독립 변수는 수치형
# 종속 변수는 범주형인 것을 확인
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [31]:
# 범주형 데이터 원핫인코딩
pd.get_dummies(아이리스)

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0     5.1  3.5    1.4   0.2          1              0             0
1     4.9  3.0    1.4   0.2          1              0             0
2     4.7  3.2    1.3   0.2          1              0             0
3     4.6  3.1    1.5   0.2          1              0             0
4     5.0  3.6    1.4   0.2          1              0             0
..    ...  ...    ...   ...        ...            ...           ...
145   6.7  3.0    5.2   2.3          0              0             1
146   6.3  2.5    5.0   1.9          0              0             1
147   6.5  3.0    5.2   2.0          0              0             1
148   6.2  3.4    5.4   2.3          0              0             1
149   5.9  3.0    5.1   1.8          0              0             1

[150 rows x 7 columns]

In [32]:
아이리스 = pd.get_dummies(아이리스)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [35]:
독립 = 아이리스[["꽃잎길이", "꽃잎폭", "꽃받침길이", "꽃받침폭"]]
종속 = 아이리스[["품종_setosa",	"품종_versicolor", "품종_virginica"]]
독립.shape, 종속.shape

((150, 4), (150, 3))

In [39]:
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation="softmax")(X)
model = tf.keras.models.Model(X, Y)

# metrics="accuracy" 분류 모델에서 정확도를 보여주는 파라미터
model.compile(loss="categorical_crossentropy", metrics="accuracy")

In [ ]:
model.fit(독립, 종속, epochs=1000)

In [42]:
model.get_weights()

[array([[ 1.3800718 ,  0.93082774, -0.31001547],
        [ 2.9355197 ,  0.47195137, -0.53229046],
        [-3.8248327 , -0.730631  ,  1.1272699 ],
        [-3.8402689 , -0.6270698 ,  2.0411127 ]], dtype=float32),
 array([ 2.0642674,  1.117904 , -1.7349473], dtype=float32)]

In [41]:
print("Predictions: ", model.predict(독립[0:5]))

1/1 [==============================] - 0s 37ms/step
Predictions:  [[9.9897838e-01 1.0214866e-03 7.1913810e-08]
 [9.9618006e-01 3.8193765e-03 5.6940189e-07]
 [9.9812263e-01 1.8771380e-03 2.4366122e-07]
 [9.9534792e-01 4.6510240e-03 1.0957632e-06]
 [9.9916458e-01 8.3528034e-04 6.0212635e-08]]


# 히든 레이어 with 보스턴

In [44]:
X = tf.keras.layers.Input(shape=[13])

# 히든 레이어, 5개의 노드
H = tf.keras.layers.Dense(5, activation='swish')(X)

# 히든 레이어, 5개의 노드
H = tf.keras.layers.Dense(5, activation='swish')(X)

# 히든 레이어, 5개의 노드
H = tf.keras.layers.Dense(5, activation='swish')(X)

# 주의할 점 : X 대신 H를 입력
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss="mse")

In [51]:
model.fit(독립_보스턴, 종속_보스턴, epochs=1000, verbose=0)
model.fit(독립_보스턴, 종속_보스턴, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 21.1811
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 20.4410
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 21.6264
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 20.8863
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 21.4404
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 20.8557
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 20.4468
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 21.5674
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 20.5665
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 20.3826


In [52]:
# 모델 모양 확인
model.summary()

Model: "model_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_7 (InputLayer)        [(None, 13)]              0         
                                                                 
 dense_9 (Dense)             (None, 5)                 70        
                                                                 
 dense_10 (Dense)            (None, 1)                 6         
                                                                 
Total params: 76
Trainable params: 76
Non-trainable params: 0
_________________________________________________________________


In [53]:
print(model.predict(독립_보스턴[:5]))
print(종속_보스턴[:5])

1/1 [==============================] - 0s 19ms/step
[[29.76599 ]
 [24.26697 ]
 [29.427034]
 [29.512484]
 [29.137846]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


# 히든 레이어 with 아이리스

In [54]:
# 입력층
X = tf.keras.layers.Input(shape=[4])

# 은닉층
H = tf.keras.layers.Dense(8, activation='swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(X)

# 출력층
Y = tf.keras.layers.Dense(3, activation="softmax")(H)

model = tf.keras.models.Model(X, Y)
model.compile(loss="categorical_crossentropy", metrics="accuracy")

In [55]:
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0568 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0552 - accuracy: 0.9867
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0552 - accuracy: 0.9800
Epoch 4/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0573 - accuracy: 0.9733
Epoch 5/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0553 - accuracy: 0.9800
Epoch 6/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0580 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 5ms/step - loss: 0.0546 - accuracy: 0.9867
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0553 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0546 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0547 - accuracy: 0.9733


In [56]:
print(model.predict(독립[0:5]))
print(종속[0:5])

1/1 [==============================] - 0s 56ms/step
[[9.9999988e-01 1.1987522e-07 3.8824539e-24]
 [9.9999881e-01 1.2443393e-06 1.0256136e-21]
 [9.9999964e-01 4.0392689e-07 1.9115799e-22]
 [9.9999690e-01 3.1423635e-06 1.6802426e-20]
 [9.9999988e-01 9.9271588e-08 3.5373478e-24]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


# 데이터 타입 조정

In [57]:
파일경로 = "https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris2.csv"

아이리스 = pd.read_csv(파일경로)

# 품종 데이터가 범주형이나 숫자로 되어있음
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종
0   5.1  3.5    1.4   0.2   0
1   4.9  3.0    1.4   0.2   0
2   4.7  3.2    1.3   0.2   0
3   4.6  3.1    1.5   0.2   0
4   5.0  3.6    1.4   0.2   0

In [58]:
# 원핫인코딩
# 범주형 데이터가 숫자로 되어있는 경우 원핫인코딩이 되지 않음
인코딩 = pd.get_dummies(아이리스)
인코딩.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종
0   5.1  3.5    1.4   0.2   0
1   4.9  3.0    1.4   0.2   0
2   4.7  3.2    1.3   0.2   0
3   4.6  3.1    1.5   0.2   0
4   5.0  3.6    1.4   0.2   0

In [61]:
# type 역시 int 인 것을 확인
아이리스.dtypes

꽃잎길이     float64
꽃잎폭      float64
꽃받침길이    float64
꽃받침폭     float64
품종         int64
dtype: object

In [64]:
# 품종 타입을 범주형으로 변환
아이리스["품종"] = 아이리스["품종"].astype("category")

In [65]:
# 잘 변환된 것 확인
아이리스.dtypes

꽃잎길이      float64
꽃잎폭       float64
꽃받침길이     float64
꽃받침폭      float64
품종       category
dtype: object

In [66]:
# 원핫인코딩이 된 것을 확인
인코딩 = pd.get_dummies(아이리스)
인코딩.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_0  품종_1  품종_2
0   5.1  3.5    1.4   0.2     1     0     0
1   4.9  3.0    1.4   0.2     1     0     0
2   4.7  3.2    1.3   0.2     1     0     0
3   4.6  3.1    1.5   0.2     1     0     0
4   5.0  3.6    1.4   0.2     1     0     0

# 결측치 처리

In [67]:
아이리스.isna().sum()

꽃잎길이     0
꽃잎폭      1
꽃받침길이    0
꽃받침폭     0
품종       0
dtype: int64

In [68]:
아이리스.tail()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭 품종
145   6.7  3.0    5.2   2.3  2
146   6.3  2.5    5.0   1.9  2
147   6.5  3.0    5.2   2.0  2
148   6.2  3.4    5.4   2.3  2
149   5.9  NaN    5.1   1.8  2

In [69]:
# 결측치 평균값으로 대체
mean = 아이리스["꽃잎폭"].mean()
아이리스["꽃잎폭"] = 아이리스["꽃잎폭"].fillna(mean)
아이리스.tail()

꽃잎길이       꽃잎폭  꽃받침길이  꽃받침폭 품종
145   6.7  3.000000    5.2   2.3  2
146   6.3  2.500000    5.0   1.9  2
147   6.5  3.000000    5.2   2.0  2
148   6.2  3.400000    5.4   2.3  2
149   5.9  3.054362    5.1   1.8  2

# 학습이 잘 되는 모델 with 보스턴

In [70]:
X = tf.keras.layers.Input(shape=[13])

# 히든 레이어, 8개의 노드
H = tf.keras.layers.Dense(8, activation='swish')(X)

# 히든 레이어, 8개의 노드
H = tf.keras.layers.Dense(8, activation='swish')(X)

# 히든 레이어, 8개의 노드
H = tf.keras.layers.Dense(8, activation='swish')(X)

# 주의할 점 : X 대신 H를 입력
Y = tf.keras.layers.Dense(1)(H)
model1 = tf.keras.models.Model(X, Y)
model1.compile(loss="mse")

In [71]:
model1.fit(독립_보스턴, 종속_보스턴, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 4679.5244
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 3532.9314
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 2844.6975
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 2361.3662
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 1984.4084
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 1720.2124
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 1547.9493
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 1402.3154
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 1258.8680
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 1135.7430


In [72]:
X = tf.keras.layers.Input(shape=[13])

H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation("swish")(H)

H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation("swish")(H)

H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation("swish")(H)

Y = tf.keras.layers.Dense(1)(H)
model2 = tf.keras.models.Model(X, Y)
model2.compile(loss="mse")

In [73]:
# 똑같이 10번 학습해도 훨씬 낮은 loss 값
model2.fit(독립_보스턴, 종속_보스턴, epochs=10)

Epoch 1/10
16/16 [==============================] - 1s 2ms/step - loss: 589.0052
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 584.2699
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 580.1451
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 576.2182
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 572.3142
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 568.3708
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 564.6317
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 560.7515
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 556.4454
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 552.4409
